get:
  description: Returns a client application by ID
  operationId: getClientApplicationById
  parameters:
    - name: id
      in: path
      description: ID of client application to fetch
      required: true
      schema:
        type: string
        format: uuid
  responses:
    "200":
      description: client application response
      content:
        application/json:
          schema:
            $ref: "../../core-schema.yaml#/components/schemas/ClientApplication"
put:
  description: Updates a client application
  operationId: updateClientApplication
  parameters:
    - name: id
      in: path
      description: ID of client application to update
      required: true
      schema:
        type: string
        format: uuid
  requestBody:
    description: Client application to update
    required: true
    content:
      application/json:
        schema:
          $ref: "../../core-schema.yaml#/components/schemas/NewClientApplication"
  responses:
    "200":
      description: client application updated
      content:
        application/json:
          schema:
            $ref: "../../core-schema.yaml#/components/schemas/ClientApplication"
delete:
  description: Deletes a client application
  operationId: deleteClientApplication
  parameters:
    - name: id
      in: path
      description: ID of client application to delete
      required: true
      schema:
        type: string
        format: uuid
  responses:
    "204":
      description: client application deleted
