#oapi-codegen -config ./openapi/parts/admin/oapi-schema-config.yaml ./openapi/parts/admin/core-schema.yaml
package: core
output: api/openapi/core/core-schema.go
generate:
  models: true
output-options:
  # to make sure that all types are generated
  skip-prune: true
