// Package core provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package core

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for APITokenStatus.
const (
	APITokenStatusACTIVE  APITokenStatus = "ACTIVE"
	APITokenStatusEXPIRED APITokenStatus = "EXPIRED"
	APITokenStatusREVOKED APITokenStatus = "REVOKED"
)

// Defines values for APITokenAuditLogAction.
const (
	APITokenAuditLogActionCREATED APITokenAuditLogAction = "CREATED"
	APITokenAuditLogActionREVOKED APITokenAuditLogAction = "REVOKED"
	APITokenAuditLogActionUPDATED APITokenAuditLogAction = "UPDATED"
	APITokenAuditLogActionUSED    APITokenAuditLogAction = "USED"
)

// Defines values for CheckDetailsStatus.
const (
	CheckDetailsStatusFail CheckDetailsStatus = "fail"
	CheckDetailsStatusPass CheckDetailsStatus = "pass"
	CheckDetailsStatusWarn CheckDetailsStatus = "warn"
)

// Defines values for HealthResponseChecksStatus.
const (
	HealthResponseChecksStatusFail HealthResponseChecksStatus = "fail"
	HealthResponseChecksStatusPass HealthResponseChecksStatus = "pass"
	HealthResponseChecksStatusWarn HealthResponseChecksStatus = "warn"
)

// Defines values for HealthResponseStatus.
const (
	Fail HealthResponseStatus = "fail"
	Pass HealthResponseStatus = "pass"
	Warn HealthResponseStatus = "warn"
)

// Defines values for NewPromptFormat.
const (
	NewPromptFormatJson     NewPromptFormat = "json"
	NewPromptFormatMarkdown NewPromptFormat = "markdown"
	NewPromptFormatText     NewPromptFormat = "text"
)

// Defines values for PromptFormat.
const (
	PromptFormatJson     PromptFormat = "json"
	PromptFormatMarkdown PromptFormat = "markdown"
	PromptFormatText     PromptFormat = "text"
)

// Defines values for Role.
const (
	ADMIN      Role = "ADMIN"
	SUPERADMIN Role = "SUPER_ADMIN"
)

// Defines values for UserActionSchemaName.
const (
	DISABLED      UserActionSchemaName = "DISABLED"
	EMAILVERIFIED UserActionSchemaName = "EMAIL_VERIFIED"
)

// APIToken defines model for APIToken.
type APIToken struct {
	// ApplicationName Name of the client application
	ApplicationName string `json:"applicationName"`

	// ClientApplicationId ID of the client application this token belongs to
	ClientApplicationId openapi_types.UUID `json:"clientApplicationId"`

	// CreatedAt Token creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy User ID of the token creator
	CreatedBy   string             `json:"createdBy"`
	Description *string            `json:"description,omitempty"`
	ExpiresAt   time.Time          `json:"expiresAt"`
	Id          openapi_types.UUID `json:"id"`

	// LastUsedAt Last used timestamp
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`

	// LastUsedIp Last used IP address
	LastUsedIp *string `json:"lastUsedIp,omitempty"`
	Name       string  `json:"name"`

	// Revoked Whether this token has been revoked
	Revoked bool `json:"revoked"`

	// RevokedAt Token revoked at timestamp
	RevokedAt *time.Time `json:"revokedAt,omitempty"`

	// RevokedBy User of the token revoker
	RevokedBy *string `json:"revokedBy,omitempty"`

	// RevokedReason Revoked reason
	RevokedReason *string `json:"revokedReason,omitempty"`

	// Scopes Permission scopes for this token
	Scopes *[]string      `json:"scopes"`
	Status APITokenStatus `json:"status"`

	// TokenPrefix First few characters of the token for identification
	TokenPrefix string `json:"tokenPrefix"`

	// UpdatedAt Token last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// APITokenStatus defines model for APIToken.Status.
type APITokenStatus string

// APITokenAuditLog defines model for APITokenAuditLog.
type APITokenAuditLog struct {
	Action         APITokenAuditLogAction  `json:"action"`
	AdditionalData *map[string]interface{} `json:"additionalData"`
	Id             openapi_types.UUID      `json:"id"`
	IpAddress      *string                 `json:"ipAddress"`
	Timestamp      time.Time               `json:"timestamp"`
	TokenId        openapi_types.UUID      `json:"tokenId"`
	UserAgent      *string                 `json:"userAgent"`
}

// APITokenAuditLogAction defines model for APITokenAuditLog.Action.
type APITokenAuditLogAction string

// APITokenCreated defines model for APITokenCreated.
type APITokenCreated struct {
	ApiToken APIToken `json:"apiToken"`

	// Token The full token value (only returned once upon creation)
	Token string `json:"token"`
}

// APITokenRevoke defines model for APITokenRevoke.
type APITokenRevoke struct {
	Reason string `json:"reason"`
}

// BasicEntity defines model for BasicEntity.
type BasicEntity struct {
	Icon *string            `json:"icon,omitempty"`
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// CheckDetails defines model for CheckDetails.
type CheckDetails struct {
	// ComponentName The name of the component being checked
	ComponentName *string `json:"componentName,omitempty"`

	// ComponentType The type of component (e.g., database, cache, external service)
	ComponentType string `json:"componentType"`

	// Output Any additional information or error output for this check
	Output *string `json:"output,omitempty"`

	// Status The status of this particular component
	Status CheckDetailsStatus `json:"status"`

	// Time The time at which this check was performed
	Time *time.Time `json:"time,omitempty"`
}

// CheckDetailsStatus The status of this particular component
type CheckDetailsStatus string

// ClientApplication defines model for ClientApplication.
type ClientApplication struct {
	Active      bool               `json:"active"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	LastUsed    *time.Time         `json:"lastUsed,omitempty"`
	LastUsedAt  *time.Time         `json:"lastUsedAt,omitempty"`
	Name        string             `json:"name"`

	// TenantId If null, this is a global application managed by SUPER_ADMIN
	TenantId *string `json:"tenantId"`
}

// ColorSchema defines model for ColorSchema.
type ColorSchema struct {
	Accent     *string `json:"accent,omitempty"`
	Background *string `json:"background,omitempty"`
	Info       *string `json:"info,omitempty"`
	Negative   *string `json:"negative,omitempty"`
	Positive   *string `json:"positive,omitempty"`
	Primary    *string `json:"primary,omitempty"`
	Secondary  *string `json:"secondary,omitempty"`
	Tertiary   *string `json:"tertiary,omitempty"`
	Text       *string `json:"text,omitempty"`
	Warning    *string `json:"warning,omitempty"`
}

// Config defines model for Config.
type Config struct {
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`
	Value *string            `json:"value,omitempty"`
}

// ErrorSchema defines model for ErrorSchema.
type ErrorSchema struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Checks Detailed health check results for API components or dependencies
	Checks *map[string]struct {
		// ComponentName The name of the component being checked
		ComponentName *string `json:"componentName,omitempty"`

		// ComponentType The type of component (e.g., database, cache, external service)
		ComponentType string `json:"componentType"`

		// Output Any additional information or error output for this check
		Output *string `json:"output,omitempty"`

		// Status The status of this particular component
		Status HealthResponseChecksStatus `json:"status"`

		// Time The time at which this check was performed
		Time *time.Time `json:"time,omitempty"`
	} `json:"checks,omitempty"`

	// Notes Array of notes relevant to current state of health
	Notes *[]string `json:"notes,omitempty"`

	// Output Raw error output, in case of "fail" or "warn" states
	Output *string `json:"output,omitempty"`

	// ReleaseId An identifier for this deployment or release of the API
	ReleaseId *string `json:"releaseId,omitempty"`

	// Status The overall health status of the API
	Status HealthResponseStatus `json:"status"`

	// Version The version of the API
	Version string `json:"version"`
}

// HealthResponseChecksStatus The status of this particular component
type HealthResponseChecksStatus string

// HealthResponseStatus The overall health status of the API
type HealthResponseStatus string

// NewAPIToken defines model for NewAPIToken.
type NewAPIToken struct {
	// ApplicationName Name of the client application
	ApplicationName string `json:"applicationName"`

	// ClientApplicationId ID of the client application this token belongs to
	ClientApplicationId openapi_types.UUID `json:"clientApplicationId"`
	Description         *string            `json:"description,omitempty"`
	ExpiresAt           time.Time          `json:"expiresAt"`
	Name                string             `json:"name"`

	// Scopes Permission scopes for this token
	Scopes *[]string `json:"scopes"`

	// TokenPrefix First few characters of the token for identification
	TokenPrefix string `json:"tokenPrefix"`
}

// NewClientApplication defines model for NewClientApplication.
type NewClientApplication struct {
	Active      bool       `json:"active"`
	Description string     `json:"description"`
	LastUsed    *time.Time `json:"lastUsed,omitempty"`
	Name        string     `json:"name"`
}

// NewConfig defines model for NewConfig.
type NewConfig struct {
	Name  string  `json:"name"`
	Value *string `json:"value,omitempty"`
}

// NewPrompt defines model for NewPrompt.
type NewPrompt struct {
	Content string `json:"content"`

	// Format Output format of the prompt execution
	Format NewPromptFormat `json:"format"`

	// FormatInstructions Instructions for the LLM on how to format the output
	FormatInstructions string   `json:"formatInstructions"`
	Name               string   `json:"name"`
	Parameters         []string `json:"parameters"`

	// SampleParameters Example parameter values for the prompt
	SampleParameters *map[string]string `json:"sampleParameters,omitempty"`
	Tags             []string           `json:"tags"`
}

// NewPromptFormat Output format of the prompt execution
type NewPromptFormat string

// NewTenant defines model for NewTenant.
type NewTenant struct {
	AllowPasswordSignUp   bool   `json:"allow_password_sign_up"`
	EnableEmailLinkSignIn bool   `json:"enable_email_link_sign_in"`
	Name                  string `json:"name"`
	Subdomain             string `json:"subdomain"`
}

// NewTranslation defines model for NewTranslation.
type NewTranslation struct {
	EntityId   openapi_types.UUID `json:"entity_id"`
	EntityType string             `json:"entity_type"`
	Field      string             `json:"field"`
	Language   string             `json:"language"`
	Value      string             `json:"value"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Email string `json:"email"`
	Name  string `json:"name"`
	Roles []Role `json:"roles"`
}

// Prompt defines model for Prompt.
type Prompt struct {
	Content string `json:"content"`

	// Format Output format of the prompt execution
	Format PromptFormat `json:"format"`

	// FormatInstructions Instructions for the LLM on how to format the output
	FormatInstructions string             `json:"formatInstructions"`
	Id                 openapi_types.UUID `json:"id"`
	Name               string             `json:"name"`
	Parameters         []string           `json:"parameters"`

	// SampleParameters Example parameter values for the prompt
	SampleParameters *map[string]string `json:"sampleParameters,omitempty"`
	Tags             []string           `json:"tags"`
}

// PromptFormat Output format of the prompt execution
type PromptFormat string

// PromptResponse defines model for PromptResponse.
type PromptResponse struct {
	Result string `json:"result"`
}

// PublicTenantSchema defines model for PublicTenantSchema.
type PublicTenantSchema struct {
	AllowPasswordSignUp   bool `json:"allow_password_sign_up"`
	EnableEmailLinkSignIn bool `json:"enable_email_link_sign_in"`

	// Features Dynamic feature flags for tenants. Each key represents a feature name and the boolean value indicates if it's enabled
	Features map[string]bool    `json:"features"`
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Profile  struct {
		DarkColors struct {
			Accent     *string `json:"accent,omitempty"`
			Background *string `json:"background,omitempty"`
			Info       *string `json:"info,omitempty"`
			Negative   *string `json:"negative,omitempty"`
			Positive   *string `json:"positive,omitempty"`
			Primary    *string `json:"primary,omitempty"`
			Secondary  *string `json:"secondary,omitempty"`
			Tertiary   *string `json:"tertiary,omitempty"`
			Text       *string `json:"text,omitempty"`
			Warning    *string `json:"warning,omitempty"`
		} `json:"darkColors"`
		DisplayName string `json:"displayName"`
		LightColors struct {
			Accent     *string `json:"accent,omitempty"`
			Background *string `json:"background,omitempty"`
			Info       *string `json:"info,omitempty"`
			Negative   *string `json:"negative,omitempty"`
			Positive   *string `json:"positive,omitempty"`
			Primary    *string `json:"primary,omitempty"`
			Secondary  *string `json:"secondary,omitempty"`
			Tertiary   *string `json:"tertiary,omitempty"`
			Text       *string `json:"text,omitempty"`
			Warning    *string `json:"warning,omitempty"`
		} `json:"lightColors"`
		Values *string `json:"values,omitempty"`
	} `json:"profile"`
	Subdomain string `json:"subdomain"`
	TenantId  string `json:"tenant_id"`
}

// Role defines model for Role.
type Role string

// Tenant defines model for Tenant.
type Tenant struct {
	AllowPasswordSignUp   bool               `json:"allow_password_sign_up"`
	EnableEmailLinkSignIn bool               `json:"enable_email_link_sign_in"`
	Id                    openapi_types.UUID `json:"id"`
	Name                  string             `json:"name"`
	Subdomain             string             `json:"subdomain"`
	TenantId              string             `json:"tenant_id"`
}

// TenantFeatures Dynamic feature flags for tenants. Each key represents a feature name and the boolean value indicates if it's enabled
type TenantFeatures map[string]bool

// TenantProfile defines model for TenantProfile.
type TenantProfile struct {
	DarkColors struct {
		Accent     *string `json:"accent,omitempty"`
		Background *string `json:"background,omitempty"`
		Info       *string `json:"info,omitempty"`
		Negative   *string `json:"negative,omitempty"`
		Positive   *string `json:"positive,omitempty"`
		Primary    *string `json:"primary,omitempty"`
		Secondary  *string `json:"secondary,omitempty"`
		Tertiary   *string `json:"tertiary,omitempty"`
		Text       *string `json:"text,omitempty"`
		Warning    *string `json:"warning,omitempty"`
	} `json:"darkColors"`
	DisplayName string `json:"displayName"`
	LightColors struct {
		Accent     *string `json:"accent,omitempty"`
		Background *string `json:"background,omitempty"`
		Info       *string `json:"info,omitempty"`
		Negative   *string `json:"negative,omitempty"`
		Positive   *string `json:"positive,omitempty"`
		Primary    *string `json:"primary,omitempty"`
		Secondary  *string `json:"secondary,omitempty"`
		Tertiary   *string `json:"tertiary,omitempty"`
		Text       *string `json:"text,omitempty"`
		Warning    *string `json:"warning,omitempty"`
	} `json:"lightColors"`
	Values *string `json:"values,omitempty"`
}

// Translation defines model for Translation.
type Translation struct {
	CreatedAt  time.Time          `json:"created_at"`
	EntityId   openapi_types.UUID `json:"entity_id"`
	EntityType string             `json:"entity_type"`
	Field      string             `json:"field"`
	Id         openapi_types.UUID `json:"id"`
	Language   string             `json:"language"`
	SortOrder  *int               `json:"sort_order,omitempty"`
	UpdatedAt  time.Time          `json:"updated_at"`
	Value      string             `json:"value"`
}

// User defines model for User.
type User struct {
	CreatedAt     *time.Time         `json:"created_at,omitempty"`
	Disabled      *bool              `json:"disabled,omitempty"`
	Email         string             `json:"email"`
	EmailVerified *bool              `json:"email_verified,omitempty"`
	Id            string             `json:"id"`
	Name          string             `json:"name"`
	Profile       *UserProfileSchema `json:"profile,omitempty"`
	Roles         []Role             `json:"roles"`
}

// UserActionSchema defines model for UserActionSchema.
type UserActionSchema struct {
	Name  UserActionSchemaName `json:"name"`
	Value bool                 `json:"value"`
}

// UserActionSchemaName defines model for UserActionSchema.Name.
type UserActionSchemaName string

// UserProfileSchema defines model for UserProfileSchema.
type UserProfileSchema struct {
	About                *string   `json:"about,omitempty"`
	BackgroundPictureURL *string   `json:"backgroundPictureURL,omitempty"`
	Interests            *[]string `json:"interests,omitempty"`
	Name                 string    `json:"name"`
	PictureURL           *string   `json:"pictureURL,omitempty"`
	Skills               *[]string `json:"skills,omitempty"`
	SocialMedias         *[]string `json:"socialMedias,omitempty"`
	Title                *string   `json:"title,omitempty"`
}
