// Package core provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package core

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for APITokenStatus.
const (
	APITokenStatusACTIVE  APITokenStatus = "ACTIVE"
	APITokenStatusEXPIRED APITokenStatus = "EXPIRED"
	APITokenStatusREVOKED APITokenStatus = "REVOKED"
)

// Defines values for APITokenAuditLogAction.
const (
	APITokenAuditLogActionCREATED APITokenAuditLogAction = "CREATED"
	APITokenAuditLogActionREVOKED APITokenAuditLogAction = "REVOKED"
	APITokenAuditLogActionUPDATED APITokenAuditLogAction = "UPDATED"
	APITokenAuditLogActionUSED    APITokenAuditLogAction = "USED"
)

// Defines values for AccountDeletionStatus.
const (
	None      AccountDeletionStatus = "none"
	Scheduled AccountDeletionStatus = "scheduled"
)

// Defines values for CheckDetailsStatus.
const (
	CheckDetailsStatusFail CheckDetailsStatus = "fail"
	CheckDetailsStatusPass CheckDetailsStatus = "pass"
	CheckDetailsStatusWarn CheckDetailsStatus = "warn"
)

// Defines values for HealthResponseChecksStatus.
const (
	HealthResponseChecksStatusFail HealthResponseChecksStatus = "fail"
	HealthResponseChecksStatusPass HealthResponseChecksStatus = "pass"
	HealthResponseChecksStatusWarn HealthResponseChecksStatus = "warn"
)

// Defines values for HealthResponseStatus.
const (
	Fail HealthResponseStatus = "fail"
	Pass HealthResponseStatus = "pass"
	Warn HealthResponseStatus = "warn"
)

// Defines values for LeaveDecisionAction.
const (
	LeaveDecisionActionCancelAtPeriodEnd LeaveDecisionAction = "cancelAtPeriodEnd"
	LeaveDecisionActionKeep              LeaveDecisionAction = "keep"
	LeaveDecisionActionTransfer          LeaveDecisionAction = "transfer"
	LeaveDecisionActionUnpublish         LeaveDecisionAction = "unpublish"
)

// Defines values for LeaveImpactActions.
const (
	LeaveImpactActionsCancelAtPeriodEnd LeaveImpactActions = "cancelAtPeriodEnd"
	LeaveImpactActionsKeep              LeaveImpactActions = "keep"
	LeaveImpactActionsTransfer          LeaveImpactActions = "transfer"
	LeaveImpactActionsUnpublish         LeaveImpactActions = "unpublish"
)

// Defines values for LeaveImpactSeverity.
const (
	Decision LeaveImpactSeverity = "decision"
	Info     LeaveImpactSeverity = "info"
)

// Defines values for LeaveTenantResultMembershipStatus.
const (
	LeaveTenantResultMembershipStatusInactive LeaveTenantResultMembershipStatus = "inactive"
)

// Defines values for MFAStatusAal.
const (
	Aal1 MFAStatusAal = "aal1"
	Aal2 MFAStatusAal = "aal2"
)

// Defines values for Role.
const (
	ADMIN         Role = "ADMIN"
	CUSTOMERADMIN Role = "CUSTOMER_ADMIN"
	SUPERADMIN    Role = "SUPER_ADMIN"
	USER          Role = "USER"
)

// Defines values for TenantLeaveDecisionAction.
const (
	CancelAtPeriodEnd TenantLeaveDecisionAction = "cancelAtPeriodEnd"
	Keep              TenantLeaveDecisionAction = "keep"
	Transfer          TenantLeaveDecisionAction = "transfer"
	Unpublish         TenantLeaveDecisionAction = "unpublish"
)

// Defines values for TenantMembershipStatus.
const (
	TenantMembershipStatusActive   TenantMembershipStatus = "active"
	TenantMembershipStatusInactive TenantMembershipStatus = "inactive"
	TenantMembershipStatusPending  TenantMembershipStatus = "pending"
	TenantMembershipStatusRejected TenantMembershipStatus = "rejected"
)

// Defines values for UserActionSchemaName.
const (
	DISABLED      UserActionSchemaName = "DISABLED"
	EMAILVERIFIED UserActionSchemaName = "EMAIL_VERIFIED"
)

// APIToken defines model for APIToken.
type APIToken struct {
	// ClientApplicationId ID of the client application this token belongs to
	ClientApplicationId openapi_types.UUID `json:"clientApplicationId"`

	// CreatedAt Token creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy User ID of the token creator
	CreatedBy   string             `json:"createdBy"`
	Description *string            `json:"description,omitempty"`
	ExpiresAt   time.Time          `json:"expiresAt"`
	Id          openapi_types.UUID `json:"id"`

	// LastUsedAt Last used timestamp
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`

	// LastUsedIp Last used IP address
	LastUsedIp *string `json:"lastUsedIp,omitempty"`
	Name       string  `json:"name"`

	// Revoked Whether this token has been revoked
	Revoked bool `json:"revoked"`

	// RevokedAt Token revoked at timestamp
	RevokedAt *time.Time `json:"revokedAt,omitempty"`

	// RevokedBy User of the token revoker
	RevokedBy *string `json:"revokedBy,omitempty"`

	// RevokedReason Revoked reason
	RevokedReason *string `json:"revokedReason,omitempty"`

	// Scopes Permission scopes for this token
	Scopes *[]string      `json:"scopes"`
	Status APITokenStatus `json:"status"`

	// TokenPrefix First few characters of the token for identification
	TokenPrefix string `json:"tokenPrefix"`

	// UpdatedAt Token last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// APITokenStatus defines model for APIToken.Status.
type APITokenStatus string

// APITokenAuditLog defines model for APITokenAuditLog.
type APITokenAuditLog struct {
	Action         APITokenAuditLogAction  `json:"action"`
	AdditionalData *map[string]interface{} `json:"additionalData"`
	Id             openapi_types.UUID      `json:"id"`
	IpAddress      *string                 `json:"ipAddress"`
	Timestamp      time.Time               `json:"timestamp"`
	TokenId        openapi_types.UUID      `json:"tokenId"`
	UserAgent      *string                 `json:"userAgent"`
}

// APITokenAuditLogAction defines model for APITokenAuditLog.Action.
type APITokenAuditLogAction string

// APITokenCreated defines model for APITokenCreated.
type APITokenCreated struct {
	ApiToken APIToken `json:"apiToken"`

	// Token The full token value (only returned once upon creation)
	Token string `json:"token"`
}

// APITokenRevoke defines model for APITokenRevoke.
type APITokenRevoke struct {
	Reason string `json:"reason"`
}

// AccountClosurePreview One entry per active membership. Closing ends them all, so the caller is shown every organization's cost at once rather than discovering them one at a time after the fact.
type AccountClosurePreview struct {
	Tenants []TenantClosureImpact `json:"tenants"`
}

// AccountDeletion defines model for AccountDeletion.
type AccountDeletion struct {
	// ExportAvailable Whether GET /api/v1/users/me/export can still be called.
	ExportAvailable *bool `json:"exportAvailable,omitempty"`

	// ScheduledAt When the caller asked for deletion.
	ScheduledAt *time.Time `json:"scheduledAt,omitempty"`

	// ScheduledFor When the deletion executes. Until then the account can be recovered by signing in and cancelling; after it, nothing is recoverable.
	ScheduledFor *time.Time            `json:"scheduledFor,omitempty"`
	Status       AccountDeletionStatus `json:"status"`

	// TenantsAffected Memberships that end with the account.
	TenantsAffected *int `json:"tenantsAffected,omitempty"`
}

// AccountDeletionStatus defines model for AccountDeletion.Status.
type AccountDeletionStatus string

// AccountDeletionRequest defines model for AccountDeletionRequest.
type AccountDeletionRequest struct {
	// ConfirmEmail Must equal the caller's own email. Verified server-side — the typed confirmation is a real check, not a client-side speed bump.
	ConfirmEmail openapi_types.Email `json:"confirmEmail"`

	// Decisions What to do with the content the caller owns, per organization. Stored with the schedule and applied at execution — not now, so cancelling leaves nothing to undo. Anything unanswered falls back to the owning module's policy.
	Decisions *[]TenantLeaveDecision `json:"decisions,omitempty"`
	Reason    *string                `json:"reason,omitempty"`
}

// BasicEntity defines model for BasicEntity.
type BasicEntity struct {
	Icon *string            `json:"icon,omitempty"`
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// CheckDetails defines model for CheckDetails.
type CheckDetails struct {
	// ComponentName The name of the component being checked
	ComponentName *string `json:"componentName,omitempty"`

	// ComponentType The type of component (e.g., database, cache, external service)
	ComponentType string `json:"componentType"`

	// Output Any additional information or error output for this check
	Output *string `json:"output,omitempty"`

	// Status The status of this particular component
	Status CheckDetailsStatus `json:"status"`

	// Time The time at which this check was performed
	Time *time.Time `json:"time,omitempty"`
}

// CheckDetailsStatus The status of this particular component
type CheckDetailsStatus string

// ClientApplication defines model for ClientApplication.
type ClientApplication struct {
	Active      bool               `json:"active"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	LastUsed    *time.Time         `json:"lastUsed,omitempty"`
	LastUsedAt  *time.Time         `json:"lastUsedAt,omitempty"`
	Name        string             `json:"name"`

	// TenantId If null, this is a global application managed by SUPER_ADMIN
	TenantId *string `json:"tenantId"`
}

// ColorSchema defines model for ColorSchema.
type ColorSchema struct {
	Accent                   *string `json:"accent,omitempty"`
	AccentForeground         *string `json:"accent-foreground,omitempty"`
	Background               *string `json:"background,omitempty"`
	Border                   *string `json:"border,omitempty"`
	Card                     *string `json:"card,omitempty"`
	CardForeground           *string `json:"card-foreground,omitempty"`
	Chart1                   *string `json:"chart-1,omitempty"`
	Chart2                   *string `json:"chart-2,omitempty"`
	Chart3                   *string `json:"chart-3,omitempty"`
	Chart4                   *string `json:"chart-4,omitempty"`
	Chart5                   *string `json:"chart-5,omitempty"`
	Destructive              *string `json:"destructive,omitempty"`
	Foreground               *string `json:"foreground,omitempty"`
	HeaderBackground         *string `json:"header-background,omitempty"`
	Info                     *string `json:"info,omitempty"`
	Input                    *string `json:"input,omitempty"`
	Muted                    *string `json:"muted,omitempty"`
	MutedForeground          *string `json:"muted-foreground,omitempty"`
	Negative                 *string `json:"negative,omitempty"`
	Popover                  *string `json:"popover,omitempty"`
	PopoverForeground        *string `json:"popover-foreground,omitempty"`
	Positive                 *string `json:"positive,omitempty"`
	Primary                  *string `json:"primary,omitempty"`
	PrimaryForeground        *string `json:"primary-foreground,omitempty"`
	Ring                     *string `json:"ring,omitempty"`
	Secondary                *string `json:"secondary,omitempty"`
	SecondaryForeground      *string `json:"secondary-foreground,omitempty"`
	Sidebar                  *string `json:"sidebar,omitempty"`
	SidebarAccent            *string `json:"sidebar-accent,omitempty"`
	SidebarAccentForeground  *string `json:"sidebar-accent-foreground,omitempty"`
	SidebarBorder            *string `json:"sidebar-border,omitempty"`
	SidebarForeground        *string `json:"sidebar-foreground,omitempty"`
	SidebarPrimary           *string `json:"sidebar-primary,omitempty"`
	SidebarPrimaryForeground *string `json:"sidebar-primary-foreground,omitempty"`
	SidebarRing              *string `json:"sidebar-ring,omitempty"`
	Tertiary                 *string `json:"tertiary,omitempty"`
	Text                     *string `json:"text,omitempty"`
	Warning                  *string `json:"warning,omitempty"`
}

// Config defines model for Config.
type Config struct {
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`
	Value *string            `json:"value,omitempty"`
}

// ErrorSchema defines model for ErrorSchema.
type ErrorSchema struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Checks Detailed health check results for API components or dependencies
	Checks *map[string]struct {
		// ComponentName The name of the component being checked
		ComponentName *string `json:"componentName,omitempty"`

		// ComponentType The type of component (e.g., database, cache, external service)
		ComponentType string `json:"componentType"`

		// Output Any additional information or error output for this check
		Output *string `json:"output,omitempty"`

		// Status The status of this particular component
		Status HealthResponseChecksStatus `json:"status"`

		// Time The time at which this check was performed
		Time *time.Time `json:"time,omitempty"`
	} `json:"checks,omitempty"`

	// Notes Array of notes relevant to current state of health
	Notes *[]string `json:"notes,omitempty"`

	// Output Raw error output, in case of "fail" or "warn" states
	Output *string `json:"output,omitempty"`

	// ReleaseId An identifier for this deployment or release of the API
	ReleaseId *string `json:"releaseId,omitempty"`

	// Status The overall health status of the API
	Status HealthResponseStatus `json:"status"`

	// Version The version of the API
	Version string `json:"version"`
}

// HealthResponseChecksStatus The status of this particular component
type HealthResponseChecksStatus string

// HealthResponseStatus The overall health status of the API
type HealthResponseStatus string

// Identify defines model for Identify.
type Identify struct {
	Email openapi_types.Email `json:"email"`
}

// LeaveDecision One answer to an impact the preview reported with severity `decision`.
type LeaveDecision struct {
	Action LeaveDecisionAction `json:"action"`

	// Key The impact key being answered, e.g. `lms.authoredPublishedCourses`.
	Key string `json:"key"`

	// TargetUserId Required for `transfer` — the member the content moves to.
	TargetUserId *string `json:"targetUserId,omitempty"`
}

// LeaveDecisionAction defines model for LeaveDecision.Action.
type LeaveDecisionAction string

// LeaveImpact Contributed by the module that owns the data. Core cannot enumerate it, so `key` is open-ended.
type LeaveImpact struct {
	// Actions Actions this decision accepts, in the order to offer them.
	Actions *[]LeaveImpactActions `json:"actions,omitempty"`
	Count   *int                  `json:"count,omitempty"`

	// Key Stable identifier used as a translation key by the SPA, e.g. `lms.enrollments`, `lms.authoredPublishedCourses`, `lms.activeSubscription`.
	Key string `json:"key"`

	// Label Fallback text for a key the SPA has no translation for.
	Label *string `json:"label,omitempty"`

	// Module Module that contributed this impact, e.g. `lms`.
	Module *string `json:"module,omitempty"`

	// Severity `info` is stated in the dialog. `decision` must be resolved by a matching entry in LeaveTenantRequest.decisions.
	Severity LeaveImpactSeverity `json:"severity"`
}

// LeaveImpactActions defines model for LeaveImpact.Actions.
type LeaveImpactActions string

// LeaveImpactSeverity `info` is stated in the dialog. `decision` must be resolved by a matching entry in LeaveTenantRequest.decisions.
type LeaveImpactSeverity string

// LeaveTenantPreview What leaving would cost, and nothing else. Identity and membership facts already came with the row this dialog was opened from.
type LeaveTenantPreview struct {
	// CanLeaveNow False while an impact of severity `decision` is unanswered.
	CanLeaveNow bool `json:"canLeaveNow"`

	// DormantUntil When the tenant-scoped data kept for a possible return would be purged if the caller leaves now. The membership row itself is never purged — it is what makes returning a reactivation.
	DormantUntil *time.Time    `json:"dormantUntil,omitempty"`
	Impacts      []LeaveImpact `json:"impacts"`
}

// LeaveTenantRequest defines model for LeaveTenantRequest.
type LeaveTenantRequest struct {
	// Decisions One entry per impact the preview reported with severity `decision`. Absent or incomplete, the leave is refused with 409 and the current preview.
	Decisions *[]LeaveDecision `json:"decisions,omitempty"`

	// Reason Optional, free text. Product feedback only; never gates the leave.
	Reason *string `json:"reason,omitempty"`
}

// LeaveTenantResult defines model for LeaveTenantResult.
type LeaveTenantResult struct {
	DormantUntil *time.Time `json:"dormantUntil,omitempty"`

	// MembershipStatus The row is kept, not deleted. Reactivating it is how a returning user gets their history back.
	MembershipStatus LeaveTenantResultMembershipStatus `json:"membershipStatus"`
	SeatReleased     *bool                             `json:"seatReleased,omitempty"`
}

// LeaveTenantResultMembershipStatus The row is kept, not deleted. Reactivating it is how a returning user gets their history back.
type LeaveTenantResultMembershipStatus string

// MFAStatus defines model for MFAStatus.
type MFAStatus struct {
	// Aal Current Authenticator Assurance Level
	Aal MFAStatusAal `json:"aal"`

	// AvailableMethods List of available MFA methods
	AvailableMethods []string `json:"available_methods"`

	// RecoveryCodesSet Whether recovery codes have been generated
	RecoveryCodesSet bool `json:"recovery_codes_set"`

	// TotpEnabled Whether TOTP (Authenticator App) is enabled
	TotpEnabled bool `json:"totp_enabled"`

	// WebauthnEnabled Whether WebAuthn (Security Key) is enabled
	WebauthnEnabled bool `json:"webauthn_enabled"`
}

// MFAStatusAal Current Authenticator Assurance Level
type MFAStatusAal string

// NewAPIToken defines model for NewAPIToken.
type NewAPIToken struct {
	// ClientApplicationId ID of the client application this token belongs to
	ClientApplicationId openapi_types.UUID `json:"clientApplicationId"`
	Description         *string            `json:"description,omitempty"`
	ExpiresAt           time.Time          `json:"expiresAt"`
	Name                string             `json:"name"`

	// Scopes Permission scopes for this token
	Scopes *[]string `json:"scopes"`

	// TokenPrefix First few characters of the token for identification
	TokenPrefix string `json:"tokenPrefix"`
}

// NewClientApplication defines model for NewClientApplication.
type NewClientApplication struct {
	Active      bool       `json:"active"`
	Description string     `json:"description"`
	LastUsed    *time.Time `json:"lastUsed,omitempty"`
	Name        string     `json:"name"`
}

// NewConfig defines model for NewConfig.
type NewConfig struct {
	Name  string  `json:"name"`
	Value *string `json:"value,omitempty"`
}

// NewSignUp defines model for NewSignUp.
type NewSignUp struct {
	Company     *string `json:"company,omitempty"`
	Email       string  `json:"email"`
	Function    *string `json:"function,omitempty"`
	Name        string  `json:"name"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

// NewTenant defines model for NewTenant.
type NewTenant struct {
	// AllowPasswordSignUp Auth Provider setting to Allow password sign up (can skip)
	AllowPasswordSignUp bool `json:"allow_password_sign_up"`

	// AllowSignUp Allow users to sign up for this tenant
	AllowSignUp bool `json:"allow_sign_up"`

	// ContractEndDate Optional contract expiry date. When reached, the tenant is automatically disabled.
	ContractEndDate *time.Time `json:"contract_end_date"`

	// IsDisabled When true, all API requests for this tenant are rejected with 403.
	IsDisabled *bool   `json:"is_disabled,omitempty"`
	IsReseller *bool   `json:"is_reseller,omitempty"`
	Name       string  `json:"name"`
	ResellerId *string `json:"reseller_id"`
	Subdomain  string  `json:"subdomain"`
}

// NewTranslation defines model for NewTranslation.
type NewTranslation struct {
	EntityId   openapi_types.UUID `json:"entity_id"`
	EntityType string             `json:"entity_type"`
	Field      string             `json:"field"`
	Language   string             `json:"language"`
	Value      string             `json:"value"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Email string `json:"email"`
	Name  string `json:"name"`
	Roles []Role `json:"roles"`

	// Silent When true, suppress invitation and welcome emails (both the synchronous Kratos welcome and any asynchronous onboarding follow-up).
	Silent *bool `json:"silent,omitempty"`
}

// PublicTenantSchema defines model for PublicTenantSchema.
type PublicTenantSchema struct {
	// AllowPasswordSignUp Auth Provider setting to Allow password sign up (can skip)
	AllowPasswordSignUp bool `json:"allow_password_sign_up"`

	// AllowSignUp Allow users to sign up for this tenant
	AllowSignUp bool `json:"allow_sign_up"`

	// ContractEndDate Optional contract expiry date. When reached, the tenant is automatically disabled.
	ContractEndDate *time.Time `json:"contract_end_date"`

	// FeatureLicenses License info per feature for a tenant. Key is the feature name. Only features enabled in TenantFeatures should have an entry.
	FeatureLicenses *map[string]struct {
		// Code License code for the feature
		Code string `json:"code"`

		// EndDate Optional license expiry date. When reached, the feature is automatically disabled. Omit or null for no expiry.
		EndDate *time.Time `json:"end_date"`
	} `json:"feature_licenses,omitempty"`

	// Features Dynamic feature flags for tenants. Each key represents a feature name and the boolean value indicates if it's enabled
	Features map[string]bool    `json:"features"`
	Id       openapi_types.UUID `json:"id"`

	// IsDisabled When true, all API requests for this tenant are rejected with 403.
	IsDisabled *bool  `json:"is_disabled,omitempty"`
	IsReseller *bool  `json:"is_reseller,omitempty"`
	Name       string `json:"name"`
	Profile    struct {
		DarkColors struct {
			Accent                   *string `json:"accent,omitempty"`
			AccentForeground         *string `json:"accent-foreground,omitempty"`
			Background               *string `json:"background,omitempty"`
			Border                   *string `json:"border,omitempty"`
			Card                     *string `json:"card,omitempty"`
			CardForeground           *string `json:"card-foreground,omitempty"`
			Chart1                   *string `json:"chart-1,omitempty"`
			Chart2                   *string `json:"chart-2,omitempty"`
			Chart3                   *string `json:"chart-3,omitempty"`
			Chart4                   *string `json:"chart-4,omitempty"`
			Chart5                   *string `json:"chart-5,omitempty"`
			Destructive              *string `json:"destructive,omitempty"`
			Foreground               *string `json:"foreground,omitempty"`
			HeaderBackground         *string `json:"header-background,omitempty"`
			Info                     *string `json:"info,omitempty"`
			Input                    *string `json:"input,omitempty"`
			Muted                    *string `json:"muted,omitempty"`
			MutedForeground          *string `json:"muted-foreground,omitempty"`
			Negative                 *string `json:"negative,omitempty"`
			Popover                  *string `json:"popover,omitempty"`
			PopoverForeground        *string `json:"popover-foreground,omitempty"`
			Positive                 *string `json:"positive,omitempty"`
			Primary                  *string `json:"primary,omitempty"`
			PrimaryForeground        *string `json:"primary-foreground,omitempty"`
			Ring                     *string `json:"ring,omitempty"`
			Secondary                *string `json:"secondary,omitempty"`
			SecondaryForeground      *string `json:"secondary-foreground,omitempty"`
			Sidebar                  *string `json:"sidebar,omitempty"`
			SidebarAccent            *string `json:"sidebar-accent,omitempty"`
			SidebarAccentForeground  *string `json:"sidebar-accent-foreground,omitempty"`
			SidebarBorder            *string `json:"sidebar-border,omitempty"`
			SidebarForeground        *string `json:"sidebar-foreground,omitempty"`
			SidebarPrimary           *string `json:"sidebar-primary,omitempty"`
			SidebarPrimaryForeground *string `json:"sidebar-primary-foreground,omitempty"`
			SidebarRing              *string `json:"sidebar-ring,omitempty"`
			Tertiary                 *string `json:"tertiary,omitempty"`
			Text                     *string `json:"text,omitempty"`
			Warning                  *string `json:"warning,omitempty"`
		} `json:"darkColors"`
		DisplayName string `json:"displayName"`
		LightColors struct {
			Accent                   *string `json:"accent,omitempty"`
			AccentForeground         *string `json:"accent-foreground,omitempty"`
			Background               *string `json:"background,omitempty"`
			Border                   *string `json:"border,omitempty"`
			Card                     *string `json:"card,omitempty"`
			CardForeground           *string `json:"card-foreground,omitempty"`
			Chart1                   *string `json:"chart-1,omitempty"`
			Chart2                   *string `json:"chart-2,omitempty"`
			Chart3                   *string `json:"chart-3,omitempty"`
			Chart4                   *string `json:"chart-4,omitempty"`
			Chart5                   *string `json:"chart-5,omitempty"`
			Destructive              *string `json:"destructive,omitempty"`
			Foreground               *string `json:"foreground,omitempty"`
			HeaderBackground         *string `json:"header-background,omitempty"`
			Info                     *string `json:"info,omitempty"`
			Input                    *string `json:"input,omitempty"`
			Muted                    *string `json:"muted,omitempty"`
			MutedForeground          *string `json:"muted-foreground,omitempty"`
			Negative                 *string `json:"negative,omitempty"`
			Popover                  *string `json:"popover,omitempty"`
			PopoverForeground        *string `json:"popover-foreground,omitempty"`
			Positive                 *string `json:"positive,omitempty"`
			Primary                  *string `json:"primary,omitempty"`
			PrimaryForeground        *string `json:"primary-foreground,omitempty"`
			Ring                     *string `json:"ring,omitempty"`
			Secondary                *string `json:"secondary,omitempty"`
			SecondaryForeground      *string `json:"secondary-foreground,omitempty"`
			Sidebar                  *string `json:"sidebar,omitempty"`
			SidebarAccent            *string `json:"sidebar-accent,omitempty"`
			SidebarAccentForeground  *string `json:"sidebar-accent-foreground,omitempty"`
			SidebarBorder            *string `json:"sidebar-border,omitempty"`
			SidebarForeground        *string `json:"sidebar-foreground,omitempty"`
			SidebarPrimary           *string `json:"sidebar-primary,omitempty"`
			SidebarPrimaryForeground *string `json:"sidebar-primary-foreground,omitempty"`
			SidebarRing              *string `json:"sidebar-ring,omitempty"`
			Tertiary                 *string `json:"tertiary,omitempty"`
			Text                     *string `json:"text,omitempty"`
			Warning                  *string `json:"warning,omitempty"`
		} `json:"lightColors"`
		Values *string `json:"values,omitempty"`
	} `json:"profile"`
	ResellerId *string `json:"reseller_id"`
	Subdomain  string  `json:"subdomain"`
	TenantId   string  `json:"tenant_id"`
}

// Role defines model for Role.
type Role string

// SettingsFlow Kratos settings flow object (simplified representation)
type SettingsFlow struct {
	// ExpiresAt When the flow expires
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Id Flow ID
	Id *string `json:"id,omitempty"`

	// IssuedAt When the flow was issued
	IssuedAt *time.Time `json:"issued_at,omitempty"`

	// Ui UI configuration for the flow
	Ui *struct {
		// Action URL to submit the flow to
		Action *string `json:"action,omitempty"`

		// Method HTTP method to use
		Method *string `json:"method,omitempty"`

		// Nodes Form nodes for the UI
		Nodes *[]map[string]interface{} `json:"nodes,omitempty"`
	} `json:"ui,omitempty"`
}

// SocialSignInResult defines model for SocialSignInResult.
type SocialSignInResult struct {
	// Provisioned True when this call created the tenant membership, false when the identity was already a member. Callers use it only for telemetry — either way the session is usable once the response is 200, though the client must re-read the session before relying on its roles.
	Provisioned bool `json:"provisioned"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	// AllowPasswordSignUp Auth Provider setting to Allow password sign up (can skip)
	AllowPasswordSignUp bool `json:"allow_password_sign_up"`

	// AllowSignUp Allow users to sign up for this tenant
	AllowSignUp bool `json:"allow_sign_up"`

	// ContractEndDate Optional contract expiry date. When reached, the tenant is automatically disabled.
	ContractEndDate *time.Time         `json:"contract_end_date"`
	Id              openapi_types.UUID `json:"id"`

	// IsDisabled When true, all API requests for this tenant are rejected with 403.
	IsDisabled *bool   `json:"is_disabled,omitempty"`
	IsReseller *bool   `json:"is_reseller,omitempty"`
	Name       string  `json:"name"`
	ResellerId *string `json:"reseller_id"`
	Subdomain  string  `json:"subdomain"`
	TenantId   string  `json:"tenant_id"`
}

// TenantClosureImpact defines model for TenantClosureImpact.
type TenantClosureImpact struct {
	Impacts   []LeaveImpact `json:"impacts"`
	Subdomain *string       `json:"subdomain,omitempty"`

	// TenantId Named in the response, never in a request: it identifies which answer belongs to which organization, not which tenant the call acts on.
	TenantId   string `json:"tenantId"`
	TenantName string `json:"tenantName"`
}

// TenantFeatureLicenses License info per feature for a tenant. Key is the feature name. Only features enabled in TenantFeatures should have an entry.
type TenantFeatureLicenses map[string]struct {
	// Code License code for the feature
	Code string `json:"code"`

	// EndDate Optional license expiry date. When reached, the feature is automatically disabled. Omit or null for no expiry.
	EndDate *time.Time `json:"end_date"`
}

// TenantFeatures Dynamic feature flags for tenants. Each key represents a feature name and the boolean value indicates if it's enabled
type TenantFeatures map[string]bool

// TenantLeaveDecision A LeaveDecision bound to the organization it answers for.
type TenantLeaveDecision struct {
	Action       TenantLeaveDecisionAction `json:"action"`
	Key          string                    `json:"key"`
	TargetUserId *string                   `json:"targetUserId,omitempty"`
	TenantId     string                    `json:"tenantId"`
}

// TenantLeaveDecisionAction defines model for TenantLeaveDecision.Action.
type TenantLeaveDecisionAction string

// TenantMembership One row of core_user_tenant_memberships joined to its tenant. Field names are snake_case because this payload predates its spec — it is the sqlc row, serialized as-is, and a live SPA already reads it. Renaming is a separate, breaking decision.
type TenantMembership struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// FeatureLicenses License info per feature for a tenant. Key is the feature name. Only features enabled in TenantFeatures should have an entry.
	FeatureLicenses *TenantFeatureLicenses `json:"feature_licenses,omitempty"`
	Id              openapi_types.UUID     `json:"id"`
	InvitedAt       *time.Time             `json:"invited_at"`
	InvitedBy       *string                `json:"invited_by"`

	// JoinedAt Null while pending — only an accepted membership has joined.
	JoinedAt *time.Time `json:"joined_at"`
	Roles    *[]Role    `json:"roles,omitempty"`

	// Status `inactive` is a membership that ended — left or removed. The row is kept because reactivating it is what restores a returning member's history.
	Status     TenantMembershipStatus `json:"status"`
	Subdomain  string                 `json:"subdomain"`
	TenantId   string                 `json:"tenant_id"`
	TenantName string                 `json:"tenant_name"`
	UpdatedAt  *time.Time             `json:"updated_at,omitempty"`
	UserId     string                 `json:"user_id"`
}

// TenantMembershipStatus `inactive` is a membership that ended — left or removed. The row is kept because reactivating it is what restores a returning member's history.
type TenantMembershipStatus string

// TenantProfile defines model for TenantProfile.
type TenantProfile struct {
	DarkColors struct {
		Accent                   *string `json:"accent,omitempty"`
		AccentForeground         *string `json:"accent-foreground,omitempty"`
		Background               *string `json:"background,omitempty"`
		Border                   *string `json:"border,omitempty"`
		Card                     *string `json:"card,omitempty"`
		CardForeground           *string `json:"card-foreground,omitempty"`
		Chart1                   *string `json:"chart-1,omitempty"`
		Chart2                   *string `json:"chart-2,omitempty"`
		Chart3                   *string `json:"chart-3,omitempty"`
		Chart4                   *string `json:"chart-4,omitempty"`
		Chart5                   *string `json:"chart-5,omitempty"`
		Destructive              *string `json:"destructive,omitempty"`
		Foreground               *string `json:"foreground,omitempty"`
		HeaderBackground         *string `json:"header-background,omitempty"`
		Info                     *string `json:"info,omitempty"`
		Input                    *string `json:"input,omitempty"`
		Muted                    *string `json:"muted,omitempty"`
		MutedForeground          *string `json:"muted-foreground,omitempty"`
		Negative                 *string `json:"negative,omitempty"`
		Popover                  *string `json:"popover,omitempty"`
		PopoverForeground        *string `json:"popover-foreground,omitempty"`
		Positive                 *string `json:"positive,omitempty"`
		Primary                  *string `json:"primary,omitempty"`
		PrimaryForeground        *string `json:"primary-foreground,omitempty"`
		Ring                     *string `json:"ring,omitempty"`
		Secondary                *string `json:"secondary,omitempty"`
		SecondaryForeground      *string `json:"secondary-foreground,omitempty"`
		Sidebar                  *string `json:"sidebar,omitempty"`
		SidebarAccent            *string `json:"sidebar-accent,omitempty"`
		SidebarAccentForeground  *string `json:"sidebar-accent-foreground,omitempty"`
		SidebarBorder            *string `json:"sidebar-border,omitempty"`
		SidebarForeground        *string `json:"sidebar-foreground,omitempty"`
		SidebarPrimary           *string `json:"sidebar-primary,omitempty"`
		SidebarPrimaryForeground *string `json:"sidebar-primary-foreground,omitempty"`
		SidebarRing              *string `json:"sidebar-ring,omitempty"`
		Tertiary                 *string `json:"tertiary,omitempty"`
		Text                     *string `json:"text,omitempty"`
		Warning                  *string `json:"warning,omitempty"`
	} `json:"darkColors"`
	DisplayName string `json:"displayName"`
	LightColors struct {
		Accent                   *string `json:"accent,omitempty"`
		AccentForeground         *string `json:"accent-foreground,omitempty"`
		Background               *string `json:"background,omitempty"`
		Border                   *string `json:"border,omitempty"`
		Card                     *string `json:"card,omitempty"`
		CardForeground           *string `json:"card-foreground,omitempty"`
		Chart1                   *string `json:"chart-1,omitempty"`
		Chart2                   *string `json:"chart-2,omitempty"`
		Chart3                   *string `json:"chart-3,omitempty"`
		Chart4                   *string `json:"chart-4,omitempty"`
		Chart5                   *string `json:"chart-5,omitempty"`
		Destructive              *string `json:"destructive,omitempty"`
		Foreground               *string `json:"foreground,omitempty"`
		HeaderBackground         *string `json:"header-background,omitempty"`
		Info                     *string `json:"info,omitempty"`
		Input                    *string `json:"input,omitempty"`
		Muted                    *string `json:"muted,omitempty"`
		MutedForeground          *string `json:"muted-foreground,omitempty"`
		Negative                 *string `json:"negative,omitempty"`
		Popover                  *string `json:"popover,omitempty"`
		PopoverForeground        *string `json:"popover-foreground,omitempty"`
		Positive                 *string `json:"positive,omitempty"`
		Primary                  *string `json:"primary,omitempty"`
		PrimaryForeground        *string `json:"primary-foreground,omitempty"`
		Ring                     *string `json:"ring,omitempty"`
		Secondary                *string `json:"secondary,omitempty"`
		SecondaryForeground      *string `json:"secondary-foreground,omitempty"`
		Sidebar                  *string `json:"sidebar,omitempty"`
		SidebarAccent            *string `json:"sidebar-accent,omitempty"`
		SidebarAccentForeground  *string `json:"sidebar-accent-foreground,omitempty"`
		SidebarBorder            *string `json:"sidebar-border,omitempty"`
		SidebarForeground        *string `json:"sidebar-foreground,omitempty"`
		SidebarPrimary           *string `json:"sidebar-primary,omitempty"`
		SidebarPrimaryForeground *string `json:"sidebar-primary-foreground,omitempty"`
		SidebarRing              *string `json:"sidebar-ring,omitempty"`
		Tertiary                 *string `json:"tertiary,omitempty"`
		Text                     *string `json:"text,omitempty"`
		Warning                  *string `json:"warning,omitempty"`
	} `json:"lightColors"`
	Values *string `json:"values,omitempty"`
}

// Translation defines model for Translation.
type Translation struct {
	CreatedAt  time.Time          `json:"created_at"`
	EntityId   openapi_types.UUID `json:"entity_id"`
	EntityType string             `json:"entity_type"`
	Field      string             `json:"field"`
	Id         openapi_types.UUID `json:"id"`
	Language   string             `json:"language"`
	SortOrder  *int               `json:"sort_order,omitempty"`
	UpdatedAt  time.Time          `json:"updated_at"`
	Value      string             `json:"value"`
}

// User defines model for User.
type User struct {
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	Disabled      *bool      `json:"disabled,omitempty"`
	Email         string     `json:"email"`
	EmailVerified *bool      `json:"email_verified,omitempty"`
	Id            string     `json:"id"`

	// MembershipStatus Membership status (active, inactive, etc.)
	MembershipStatus *string            `json:"membership_status"`
	Name             string             `json:"name"`
	Profile          *UserProfileSchema `json:"profile,omitempty"`
	Roles            []Role             `json:"roles"`
}

// UserActionSchema defines model for UserActionSchema.
type UserActionSchema struct {
	Name  UserActionSchemaName `json:"name"`
	Value bool                 `json:"value"`
}

// UserActionSchemaName defines model for UserActionSchema.Name.
type UserActionSchemaName string

// UserDataExport Assembled by core from what it owns, plus one section per registered data contributor. Core cannot enumerate module data — `modules` is deliberately open, and its keys are the contributors that answered, which is also how a reader sees what the export covered.
type UserDataExport struct {
	ExportedAt  time.Time          `json:"exportedAt"`
	Memberships []TenantMembership `json:"memberships"`

	// Modules Keyed by contributor name (`lms`, `aiemployee`, …). The shape of each value is the contributing module's business, not core's.
	Modules map[string]interface{} `json:"modules"`
	User    User                   `json:"user"`
}

// UserProfileSchema defines model for UserProfileSchema.
type UserProfileSchema struct {
	About                *string   `json:"about,omitempty"`
	BackgroundPictureURL *string   `json:"backgroundPictureURL,omitempty"`
	Company              *string   `json:"company,omitempty"`
	Function             *string   `json:"function,omitempty"`
	Interests            *[]string `json:"interests,omitempty"`

	// IsActingReseller Whether the current tenant is a reseller of a the tenant (read-only, derived from auth claims)
	IsActingReseller *bool `json:"is_acting_reseller,omitempty"`

	// IsReseller Whether the current tenant is a reseller (read-only, derived from auth claims)
	IsReseller   *bool     `json:"is_reseller,omitempty"`
	Name         string    `json:"name"`
	PhoneNumber  *string   `json:"phoneNumber,omitempty"`
	PictureURL   *string   `json:"pictureURL,omitempty"`
	Skills       *[]string `json:"skills,omitempty"`
	SocialMedias *[]string `json:"socialMedias,omitempty"`
	Title        *string   `json:"title,omitempty"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}
