openapi: 3.0.3
info:
  title: Tenant Membership API
  description: API for managing user-tenant memberships
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/v1/users/me/tenants:
    get:
      summary: List user's tenant memberships
      description: Get all tenants the current user belongs to
      operationId: listUserTenants
      tags:
        - Tenant Membership
      security:
        - BearerAuth: []
      responses:
        "200":
          description: List of tenant memberships
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TenantMembership"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/v1/users/me/tenants/pending:
    get:
      summary: List pending invitations
      description: Get all pending tenant invitations for the current user
      operationId: listPendingInvitations
      tags:
        - Tenant Membership
      security:
        - BearerAuth: []
      responses:
        "200":
          description: List of pending invitations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TenantMembership"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/v1/users/me/tenants/{tenantId}/accept:
    post:
      summary: Accept tenant invitation
      description: Accept a pending invitation to join a tenant
      operationId: acceptTenantInvitation
      tags:
        - Tenant Membership
      security:
        - BearerAuth: []
      parameters:
        - name: tenantId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Invitation accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantMembership"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/v1/users/me/tenants/{tenantId}/reject:
    post:
      summary: Reject tenant invitation
      description: Reject a pending invitation to join a tenant
      operationId: rejectTenantInvitation
      tags:
        - Tenant Membership
      security:
        - BearerAuth: []
      parameters:
        - name: tenantId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Invitation rejected
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/v1/tenants/{tenantId}/members:
    get:
      summary: List tenant members
      description: Get all members of a tenant (requires ADMIN role)
      operationId: listTenantMembers
      tags:
        - Tenant Membership
      security:
        - BearerAuth: []
      parameters:
        - name: tenantId
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [active, pending, suspended, removed]
            default: active
      responses:
        "200":
          description: List of tenant members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TenantMember"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

    post:
      summary: Invite user to tenant
      description: Invite a user to join the tenant (requires ADMIN role)
      operationId: inviteUserToTenant
      tags:
        - Tenant Membership
      security:
        - BearerAuth: []
      parameters:
        - name: tenantId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InviteUserRequest"
      responses:
        "201":
          description: User invited
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantMembership"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/v1/tenants/{tenantId}/members/{userId}:
    patch:
      summary: Update member role
      description: Update a member's role in the tenant (requires ADMIN role)
      operationId: updateMemberRole
      tags:
        - Tenant Membership
      security:
        - BearerAuth: []
      parameters:
        - name: tenantId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMemberRoleRequest"
      responses:
        "200":
          description: Member role updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantMembership"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

    delete:
      summary: Remove member from tenant
      description: Remove a member from the tenant (requires ADMIN role)
      operationId: removeMemberFromTenant
      tags:
        - Tenant Membership
      security:
        - BearerAuth: []
      parameters:
        - name: tenantId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Member removed
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TenantMembership:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
        tenant_id:
          type: string
        tenant_name:
          type: string
        subdomain:
          type: string
        role:
          type: string
          enum: [USER, ADMIN, CUSTOMER_ADMIN]
        status:
          type: string
          enum: [pending, active, suspended, removed]
        invited_by:
          type: string
          nullable: true
        invited_at:
          type: string
          format: date-time
          nullable: true
        joined_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    TenantMember:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
          enum: [USER, ADMIN, CUSTOMER_ADMIN]
        status:
          type: string
          enum: [pending, active, suspended, removed]
        invited_by:
          type: string
          nullable: true
        invited_at:
          type: string
          format: date-time
          nullable: true
        joined_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time

    InviteUserRequest:
      type: object
      required:
        - email
        - role
      properties:
        email:
          type: string
          format: email
        role:
          type: string
          enum: [USER, ADMIN]
          default: USER

    UpdateMemberRoleRequest:
      type: object
      required:
        - role
      properties:
        role:
          type: string
          enum: [USER, ADMIN, CUSTOMER_ADMIN]

    SuccessResponse:
      type: object
      properties:
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

  responses:
    BadRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    NotFoundError:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
