// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signup_email_throttle.sql

package repository

import (
	"context"
)

const claimSignupEmailSend = `-- name: ClaimSignupEmailSend :one
INSERT INTO core_signup_email_throttle AS t (
    email_hash, last_sent_at, window_started_at, window_count
) VALUES (
    $1, clock_timestamp(), clock_timestamp(), 1
)
ON CONFLICT (email_hash) DO UPDATE SET
    last_sent_at = clock_timestamp(),
    window_started_at = CASE
        WHEN t.window_started_at <= clock_timestamp() - make_interval(secs => $2::int)
        THEN clock_timestamp() ELSE t.window_started_at END,
    window_count = CASE
        WHEN t.window_started_at <= clock_timestamp() - make_interval(secs => $2::int)
        THEN 1 ELSE t.window_count + 1 END
WHERE t.last_sent_at <= clock_timestamp() - make_interval(secs => $3::int)
  AND (
    t.window_started_at <= clock_timestamp() - make_interval(secs => $2::int)
    OR t.window_count < $4::int
  )
RETURNING t.email_hash
`

type ClaimSignupEmailSendParams struct {
	EmailHash       string `json:"email_hash"`
	WindowSeconds   int32  `json:"window_seconds"`
	CooldownSeconds int32  `json:"cooldown_seconds"`
	MaxPerWindow    int32  `json:"max_per_window"`
}

// Claims the right to send one sign-up email to an address. Returns no row when
// the address is still cooling down or has used up its window. The row lock
// taken by ON CONFLICT serialises concurrent claims across replicas.
func (q *Queries) ClaimSignupEmailSend(ctx context.Context, arg ClaimSignupEmailSendParams) (string, error) {
	row := q.db.QueryRow(ctx, claimSignupEmailSend,
		arg.EmailHash,
		arg.WindowSeconds,
		arg.CooldownSeconds,
		arg.MaxPerWindow,
	)
	var email_hash string
	err := row.Scan(&email_hash)
	return email_hash, err
}
